#!/bin/bash
name=$1
case $name in
     my)      
         bash /home/dikkidikki/Documents/bash-db-create/mydevdb.sh $2 $3 $3
          # Functions mysl
          ok() { echo -e '\e[32m'$2'\e[m'; } # Green

          EXPECTED_ARGS=3
          E_BADARGS=65
          MYSQL=`which mysql`
          
          Q1="CREATE DATABASE IF NOT EXISTS $2;"
          Q2="GRANT ALL ON *.* TO '$3'@'localhost' IDENTIFIED BY '$4';"
          Q3="FLUSH PRIVILEGES;"
          SQL="${Q1}${Q2}${Q3}"
          
          if [ $# -ne $EXPECTED_ARGS ]
          then
          echo "Usage: $0 dbname dbuser dbpass"
          exit $E_BADARGS
          fi
          
          $MYSQL -uroot -p -e "$SQL"

          ok "Database $2 and user $3 created with a password $4"

          
          ;;
     pg)      
          bash /home/dikkidikki/Documents/bash-db-create/pgdevdb.sh $2 $3
          ;;
     help)      
          echo "
GNU Dev-tool-db , version 1.0
Usage :
mysql      [my]                            usage       # my dbname user password
postgresql [pg]                            usage       #  pg dbname 
                                           usage delete# pg -d dbname 
                                           usage login # ph -l dbname 
Copyright@  dikki hryd
email: dk.harryadi@gmail.com
github: dikiharyadi19

                 "
          ;;
     *)
          echo "argument error see 'dev-db help'"
          ;;
esac


